linters-settings:
  govet:
    shadow: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/mgeorge67701/crossplane-terraform
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - funlen
    - gochecknoglobals
    - gocognit
    - godox
    - err113
    - nestif
    - prealloc
    - testpackage
    - revive
    - wsl

run:
  timeout: 10m
  go: "1.24"

issues:
  exclude-rules:
    - path: zz_generated\.deepcopy\.go
      linters:
        - lll
        - dupl
    - path: _test\.go
      linters:
        - mnd
        - lll
        - dupl
    - path: main\.go
      linters:
        - mnd
  exclude:
    - "should have a package comment"
    - "exported .* should have comment"
    - "comment on exported .* should be of the form"
