run:
  timeout: 10m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell

  disable:
    - funlen
    - gochecknoglobals
    - gocognit
    - godox
    - nestif
    - testpackage
    - revive
